name    'rocha-dmlite'
version '0.4.0'
source 'git://github.com/rochaporto/puppet-dmlite'
author 'rocha'
license 'Apache License, Version 2.0 (the "License")'
summary 'Resources for managing a dmlite installation, including all its plugins'
description ''
project_page 'https://svnweb.cern.ch/trac/lcgdm'
